/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.senac.locacao.jpa.Telas;

import br.com.senac.locacao.jpa.pesistencia.Descricao;

/**
 *
 * @author aurel
 */
public class TelaDescricao extends javax.swing.JFrame {

    public void casa1(){
        Descricao desc = new Descricao();
        desc.casa1();
    }
    public void casa2(){
        Descricao desc = new Descricao();
        desc.casa2();
    }
    public void casa3(){
        Descricao desc = new Descricao();
        desc.casa3();
    }
    public void ap1(){
        Descricao desc = new Descricao();
        desc.ap1();
    }
    public void ap2(){
        Descricao desc = new Descricao();
        desc.ap2();
    }

    public TelaDescricao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        btnLimparTotal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCasa1 = new javax.swing.JButton();
        btnCasa2 = new javax.swing.JButton();
        btnCasa3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDias1 = new javax.swing.JTextField();
        txtDias2 = new javax.swing.JTextField();
        txtDias3 = new javax.swing.JTextField();
        btnCalcular1 = new javax.swing.JButton();
        btnCalcular2 = new javax.swing.JButton();
        btnCalcular3 = new javax.swing.JButton();
        btnLimparDias = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnAp1 = new javax.swing.JButton();
        btnAp2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtAp1 = new javax.swing.JTextField();
        txtAp2 = new javax.swing.JTextField();
        btnCalcularAp1 = new javax.swing.JButton();
        btnCalcularAp2 = new javax.swing.JButton();
        btnLimparDiasAp = new javax.swing.JButton();
        btnCadastro = new javax.swing.JButton();

        jButton2.setText("jButton2");

        jLabel14.setText("jLabel14");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Descrição de Imovéis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 36), new java.awt.Color(0, 102, 153)))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 255));
        jLabel1.setText("Bertioga - INDAIA");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Valor de hospedagem =");

        btnLimparTotal.setBackground(new java.awt.Color(204, 0, 0));
        btnLimparTotal.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnLimparTotal.setText("LIMPAR");
        btnLimparTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparTotalActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Descrição Casa -1");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Descrição Casa -2");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Descrição Casa -3");

        btnCasa1.setBackground(new java.awt.Color(153, 255, 255));
        btnCasa1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnCasa1.setForeground(new java.awt.Color(0, 0, 0));
        btnCasa1.setText("VER");
        btnCasa1.setToolTipText("Clique para visualizar a descrição");
        btnCasa1.setNextFocusableComponent(txtDias1);
        btnCasa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCasa1ActionPerformed(evt);
            }
        });

        btnCasa2.setBackground(new java.awt.Color(153, 255, 255));
        btnCasa2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnCasa2.setForeground(new java.awt.Color(0, 0, 0));
        btnCasa2.setText("VER");
        btnCasa2.setToolTipText("Clique para visualizar a descrição");
        btnCasa2.setNextFocusableComponent(txtDias2);
        btnCasa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCasa2ActionPerformed(evt);
            }
        });

        btnCasa3.setBackground(new java.awt.Color(153, 255, 255));
        btnCasa3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnCasa3.setForeground(new java.awt.Color(51, 51, 51));
        btnCasa3.setText("VER");
        btnCasa3.setToolTipText("Clique para ver a descrição");
        btnCasa3.setNextFocusableComponent(txtDias3);
        btnCasa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCasa3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Digite a quantidade de Dias =");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setText("Digite a quantidade de Dias =");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setText("Digite a quantidade de Dias =");

        txtDias1.setToolTipText("Digite os dias desejado para saber o valor Total");
        txtDias1.setNextFocusableComponent(btnCalcular1);

        txtDias2.setToolTipText("Digite os dias desejado para saber o valor Total");
        txtDias2.setNextFocusableComponent(btnCalcular2);

        txtDias3.setToolTipText("Digite os dias desejado para saber o valor Total");
        txtDias3.setNextFocusableComponent(btnCalcular3);

        btnCalcular1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnCalcular1.setText("CALCULAR");
        btnCalcular1.setNextFocusableComponent(btnLimparDias);
        btnCalcular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular1ActionPerformed(evt);
            }
        });

        btnCalcular2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnCalcular2.setText("CALCULAR");
        btnCalcular2.setNextFocusableComponent(btnLimparDias);
        btnCalcular2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular2ActionPerformed(evt);
            }
        });

        btnCalcular3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnCalcular3.setText("CALCULAR");
        btnCalcular3.setNextFocusableComponent(btnLimparDias);
        btnCalcular3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular3ActionPerformed(evt);
            }
        });

        btnLimparDias.setBackground(new java.awt.Color(204, 0, 0));
        btnLimparDias.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnLimparDias.setText("LIMPAR");
        btnLimparDias.setNextFocusableComponent(btnCadastro);
        btnLimparDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparDiasActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 102, 153));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 153));
        jLabel9.setText("Praia Grande - TUPY/MARACANÃ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setText("Apartamento - 1");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel11.setText("Apartamento - 2");

        btnAp1.setBackground(new java.awt.Color(153, 255, 255));
        btnAp1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnAp1.setForeground(new java.awt.Color(0, 0, 0));
        btnAp1.setText("VER");
        btnAp1.setToolTipText("Clique para ver a descrição");
        btnAp1.setNextFocusableComponent(txtAp1);
        btnAp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAp1ActionPerformed(evt);
            }
        });

        btnAp2.setBackground(new java.awt.Color(153, 255, 255));
        btnAp2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnAp2.setForeground(new java.awt.Color(0, 0, 0));
        btnAp2.setText("VER");
        btnAp2.setToolTipText("Clique para ver a descrição");
        btnAp2.setNextFocusableComponent(txtAp2);
        btnAp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAp2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel12.setText("Digite a quantidade de Dias =");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel13.setText("Digite a quantidade de Dias =");

        txtAp1.setToolTipText("Digite os dias desejado para saber o valor Total");
        txtAp1.setNextFocusableComponent(btnCalcularAp1);

        txtAp2.setToolTipText("Digite os dias desejado para ver o valor Total");
        txtAp2.setNextFocusableComponent(btnCalcularAp2);

        btnCalcularAp1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnCalcularAp1.setText("CALCULAR");
        btnCalcularAp1.setNextFocusableComponent(btnLimparDiasAp);
        btnCalcularAp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularAp1ActionPerformed(evt);
            }
        });

        btnCalcularAp2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnCalcularAp2.setText("CALCULAR");
        btnCalcularAp2.setNextFocusableComponent(btnLimparDiasAp);
        btnCalcularAp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularAp2ActionPerformed(evt);
            }
        });

        btnLimparDiasAp.setBackground(new java.awt.Color(204, 0, 0));
        btnLimparDiasAp.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnLimparDiasAp.setText("LIMPAR");
        btnLimparDiasAp.setNextFocusableComponent(btnCadastro);
        btnLimparDiasAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparDiasApActionPerformed(evt);
            }
        });

        btnCadastro.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnCadastro.setText("RESERVAR");
        btnCadastro.setToolTipText("Clique para ser direcionado a tela de cadastro e reservar");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAp1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAp1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAp2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAp2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCalcularAp1)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimparDiasAp))
                            .addComponent(btnCalcularAp2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnCasa2)
                                        .addComponent(btnCasa3)
                                        .addComponent(btnCasa1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtDias3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtDias1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtDias2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnCalcular3)
                                        .addComponent(btnCalcular1)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnCalcular2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnLimparTotal)
                                                .addComponent(btnLimparDias))))))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(32, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(btnCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(btnLimparTotal)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnCasa1)
                    .addComponent(jLabel7)
                    .addComponent(txtDias1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnCasa2)
                    .addComponent(jLabel6)
                    .addComponent(txtDias2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular2)
                    .addComponent(btnLimparDias))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnCasa3)
                    .addComponent(jLabel8)
                    .addComponent(txtDias3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular3))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(btnAp1)
                            .addComponent(jLabel12)
                            .addComponent(txtAp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCalcularAp1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnLimparDiasAp)))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(btnAp2)
                    .addComponent(jLabel13)
                    .addComponent(txtAp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcularAp2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnCadastro)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCasa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCasa1ActionPerformed
        casa1();
    }//GEN-LAST:event_btnCasa1ActionPerformed

    private void btnCasa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCasa2ActionPerformed
       casa2();
    }//GEN-LAST:event_btnCasa2ActionPerformed

    private void btnCasa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCasa3ActionPerformed
       casa3();
    }//GEN-LAST:event_btnCasa3ActionPerformed

    private void btnAp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAp1ActionPerformed
        ap1();
    }//GEN-LAST:event_btnAp1ActionPerformed

    private void btnAp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAp2ActionPerformed
        ap2();
    }//GEN-LAST:event_btnAp2ActionPerformed

    private void btnCalcular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular1ActionPerformed
        double total;
        int dias;

        dias = Integer.parseInt(txtDias1.getText());
        total= dias*500;
        txtTotal.setText("Total " +total);

        return;

    }//GEN-LAST:event_btnCalcular1ActionPerformed

    private void btnCalcular2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular2ActionPerformed
        double total;
        int dias;

        dias = Integer.parseInt(txtDias2.getText());
        total= dias*450;
        txtTotal.setText("Total " +total);

        return;

    }//GEN-LAST:event_btnCalcular2ActionPerformed

    private void btnCalcular3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular3ActionPerformed
       double total;
        int dias;

        dias = Integer.parseInt(txtDias3.getText());
        total= dias*450;
        txtTotal.setText("Total " +total);

        return;

    }//GEN-LAST:event_btnCalcular3ActionPerformed

    private void btnCalcularAp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularAp1ActionPerformed
       double total;
        int dias;

        dias = Integer.parseInt(txtAp1.getText());
        total= dias*300;
        txtTotal.setText("Total " +total);

        return;

    }//GEN-LAST:event_btnCalcularAp1ActionPerformed

    private void btnCalcularAp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularAp2ActionPerformed
       double total;
        int dias;

        dias = Integer.parseInt(txtAp2.getText());
        total= dias*400;
        txtTotal.setText("Total " +total);

        return;

    }//GEN-LAST:event_btnCalcularAp2ActionPerformed

    private void btnLimparTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparTotalActionPerformed
               txtTotal.setText("");
    }//GEN-LAST:event_btnLimparTotalActionPerformed

    private void btnLimparDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparDiasActionPerformed
        txtDias1.setText("");
        txtDias2.setText("");
        txtDias3.setText("");

    }//GEN-LAST:event_btnLimparDiasActionPerformed

    private void btnLimparDiasApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparDiasApActionPerformed
        txtAp1.setText("");
        txtAp2.setText("");

    }//GEN-LAST:event_btnLimparDiasApActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
      TelaCadastro cad = new TelaCadastro();
      cad.setVisible(true);
    }//GEN-LAST:event_btnCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDescricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDescricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDescricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDescricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDescricao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAp1;
    private javax.swing.JButton btnAp2;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnCalcular1;
    private javax.swing.JButton btnCalcular2;
    private javax.swing.JButton btnCalcular3;
    private javax.swing.JButton btnCalcularAp1;
    private javax.swing.JButton btnCalcularAp2;
    private javax.swing.JButton btnCasa1;
    private javax.swing.JButton btnCasa2;
    private javax.swing.JButton btnCasa3;
    private javax.swing.JButton btnLimparDias;
    private javax.swing.JButton btnLimparDiasAp;
    private javax.swing.JButton btnLimparTotal;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtAp1;
    private javax.swing.JTextField txtAp2;
    private javax.swing.JTextField txtDias1;
    private javax.swing.JTextField txtDias2;
    private javax.swing.JTextField txtDias3;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
